### ISSUE TITLE
Search-based cardfinder results

### ISSUE THREAD

**Issue by jwoolley** [GoodGamery/mtgnewsbot#82]
Have cardfinder return a list of cards given a search string, either freeform ('"flip a coin") or field-specific (creature type:crocodile, cardtype:planeswalker, etc.)

**Comment by mdiehr** [comment]
If you have an idea for how the API should work you should create an issue in your repo: https://github.com/jwoolley/mtgcardfinder

Then I can work in implementing it for that lib & deploy it!

**Comment by mdiehr** [comment]
Closing, any search features we want should be added to the other repo.
