### ISSUE TITLE
"Card of the Day"

### ISSUE THREAD

**Issue by jwoolley** [GoodGamery/mtgnewsbot#88]
Card image with a simple blurb, e.g.:
![Card of the Day example](http://i.imgur.com/dOWyl0J.png)

This will require having a working cardfinder.

**Comment by mdiehr** [comment]
Cardfinder is working!
Once we have this, and the cmd-line options are available, we could have a cron run this one specifically at a specific time each day

**Comment by mdiehr** [comment]
@jwoolley do you have a link to an html page where this came from?

**Comment by jwoolley** [comment]
Just dailymtg.com, heh.

**Comment by jwoolley** [comment]
@mdiehr

**Comment by mdiehr** [comment]
working on this now

**Comment by mdiehr** [comment]
This will be fixed in https://github.com/GoodGamery/mtgnewsbot/pull/138
